dev: java11 forward compatibility
[ERROR] equalsContract(org.hosh.spi.ValuesTest$LocalPathValueTest)  Time elapsed: 0.029 s  <<< FAILURE!
java.lang.AssertionError:
UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at org.hosh.spi.ValuesTest$LocalPathValueTest.equalsContract(ValuesTest.java:135)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: