fix race condition in JLine
It happens when the user hits simultaneously ctrl-c and enter:
java.io.IOError: java.io.InterruptedIOException: Command interrupted
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:618)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:402)
	at org.hosh.runtime.LineReaderIterator.hasNext(LineReaderIterator.java:28)
	at org.hosh.Hosh.repl(Hosh.java:140)
	at org.hosh.Hosh.runWithin(Hosh.java:106)
	at org.hosh.Hosh.main(Hosh.java:69)
Caused by: java.io.InterruptedIOException: Command interrupted
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:46)
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:21)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
	... 6 more
Caused by: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at org.jline.utils.ExecHelper.waitAndCapture(ExecHelper.java:66)
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:36)
	... 11 more